version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///data_vending.db
      - SECRET_KEY=your-super-secret-key-change-this-in-production
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./data_vending.db:/app/data_vending.db
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    restart: unless-stopped